title: Michael R - GitHub
description: Engineering Complex Technologies through Elegant Simplicity
[Old] #description: Complex Technologies Engineered With Elegance Through Simplicity
show_downloads: false
google_analytics: G-SJHZ177HBE
theme: jekyll-theme-architect