title: Michael R - GitHub
description: Engineering Complex Technologies through Elegant Simplicity
### description: Complex Technologies Engineered With Elegance Through Simplicity
show_downloads: false
google_analytics: UA-452612813
theme: jekyll-theme-architect